### ISSUE TITLE
Nova 4 Support

### ISSUE THREAD

**Issue by RoliJ** [dpsoft-official/nova-persian-date#4]
Hi!

When I try to use the package using (Nova >= 4, Laravel 9, PHP >= 8), I get the following console error:

```

runtime-core.esm-bundler.js:226

TypeError: Cannot read properties of undefined (reading '_c')

    at Proxy.render (nova-persian-date:1:4331)

    at zn (runtime-core.esm-bundler.js:893:44)

    at we.fn (runtime-core.esm-bundler.js:5030:57)

    at we.run (reactivity.esm-bundler.js:167:25)

    at R (runtime-core.esm-bundler.js:5156:9)

    at j (runtime-core.esm-bundler.js:4939:9)

    at N (runtime-core.esm-bundler.js:4897:17)

    at g (runtime-core.esm-bundler.js:4489:21)

    at E (runtime-core.esm-bundler.js:4685:13)

    at B (runtime-core.esm-bundler.js:4856:13)

```
    
Does this package support Nova 4? Should I run npm commands for the package or `composer require dpsoft/nova-persian-date` is enough?

Thanks in advance!

**Comment by SadeghPM** [comment]
Hi @RoliJ 
Currently this package doesn't support Nova 4. We don't have Nova 4 to test and upgrade.

**Comment by RoliJ** [comment]
@SadeghPM Thanks!

**Comment by sinamiandashti** [comment]
any update?
